import { StyleSheet } from "react-native"
import { colors, spacing, borderRadius, fontSize, fontWeight, shadows } from "../theme"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: colors.success,
    borderBottomLeftRadius: spacing.xxxl,
    borderBottomRightRadius: spacing.xxxl,
  },
  header: {
    paddingTop: 60,
    paddingBottom: spacing.xxl,
    paddingHorizontal: spacing.xxl,
    zIndex: 1,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: spacing.xl,
  },
  titleSection: {
    flex: 1,
  },
  headerTitle: {
    fontSize: fontSize.xxxl,
    fontWeight: fontWeight.extraBold,
    color: colors.white,
    marginBottom: spacing.xs,
  },
  headerSubtitle: {
    fontSize: fontSize.md,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: fontWeight.medium,
  },
  achievementBadge: {
    backgroundColor: "rgba(251, 191, 36, 0.2)",
    borderRadius: spacing.xl,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.3)",
  },
  achievementText: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.warning,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: spacing.lg,
    padding: spacing.lg,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  statText: {
    fontSize: fontSize.sm,
    color: "rgba(255, 255, 255, 0.9)",
    fontWeight: fontWeight.semiBold,
  },
  listContainer: {
    padding: spacing.xl,
    flexGrow: 1,
    paddingTop: spacing.sm,
  },
  separator: {
    height: spacing.md,
  },
  taskItem: {
    backgroundColor: colors.white,
    borderRadius: spacing.xl,
    padding: spacing.xl,
    ...shadows.md,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  taskHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  taskBadgeCompleted: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0fdf4",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: spacing.md,
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  taskId: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.success,
  },
  completedDateBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.gray[100],
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.sm,
    gap: spacing.xs,
  },
  completedDate: {
    fontSize: fontSize.xs,
    color: colors.text.secondary,
    fontWeight: fontWeight.medium,
  },
  taskText: {
    fontSize: fontSize.md,
    color: colors.text.primary,
    lineHeight: 24,
    marginBottom: spacing.lg,
    fontWeight: fontWeight.medium,
  },
  transcriptionContainer: {
    backgroundColor: "#faf5ff",
    padding: spacing.lg,
    borderRadius: spacing.md,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: "#e9d5ff",
  },
  transcriptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  transcriptionLabel: {
    fontSize: fontSize.xs,
    color: colors.purple,
    fontWeight: fontWeight.semiBold,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  transcriptionText: {
    fontSize: fontSize.md,
    color: "#581c87",
    fontStyle: "italic",
    lineHeight: 22,
  },
  metaInfo: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: spacing.lg,
  },
  durationBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ecfeff",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.sm,
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: "#a5f3fc",
  },
  durationText: {
    fontSize: fontSize.xs,
    color: colors.info,
    fontWeight: fontWeight.semiBold,
  },
  actionButtons: {
    flexDirection: "row",
    gap: spacing.md,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: spacing.md,
    gap: spacing.xs,
  },
  playButton: {
    backgroundColor: "#f0fdf4",
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  playButtonActive: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  deleteButton: {
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  actionButtonText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semiBold,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: spacing.xxxl,
  },
  emptyIconContainer: {
    position: "relative",
    marginBottom: spacing.xxl,
  },
  emptyBadge: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: colors.primary,
    borderRadius: spacing.lg,
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyStateTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.bold,
    color: colors.text.secondary,
    marginBottom: spacing.md,
    textAlign: "center",
  },
  emptyStateText: {
    fontSize: fontSize.lg,
    color: colors.text.tertiary,
    textAlign: "center",
    lineHeight: 26,
    marginBottom: spacing.sm,
  },
  emptyStateSubtext: {
    fontSize: fontSize.md,
    color: "#cbd5e1",
    textAlign: "center",
    fontWeight: fontWeight.medium,
  },
})
