import { StyleSheet } from "react-native"
import { colors, spacing, borderRadius, fontSize, fontWeight, shadows } from "../theme"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    backgroundColor: colors.primaryLight,
    borderBottomLeftRadius: spacing.xxxl,
    borderBottomRightRadius: spacing.xxxl,
  },
  header: {
    paddingTop: 60,
    paddingBottom: spacing.xxl,
    paddingHorizontal: spacing.xxl,
    zIndex: 1,
  },
  userInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarContainer: {
    position: "relative",
    marginRight: spacing.xl,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  onlineIndicator: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: colors.white,
    borderRadius: spacing.md,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  userDetails: {
    flex: 1,
  },
  username: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.extraBold,
    color: colors.white,
    marginBottom: spacing.xs,
  },
  userEmail: {
    fontSize: fontSize.md,
    color: "rgba(255, 255, 255, 0.8)",
    marginBottom: spacing.sm,
  },
  userBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(251, 191, 36, 0.2)",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: spacing.md,
    alignSelf: "flex-start",
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.3)",
  },
  userLevel: {
    fontSize: fontSize.xs,
    color: colors.warning,
    fontWeight: fontWeight.semiBold,
  },
  syncSection: {
    backgroundColor: colors.white,
    margin: spacing.xl,
    padding: spacing.xl,
    borderRadius: spacing.xl,
    ...shadows.lg,
    borderLeftWidth: 4,
    borderLeftColor: colors.warning,
  },
  syncAlert: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  syncIcon: {
    backgroundColor: "#fffbeb",
    borderRadius: spacing.lg,
    width: 48,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.lg,
  },
  syncContent: {
    flex: 1,
  },
  syncTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.warning,
    marginBottom: 2,
  },
  syncDescription: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  syncButton: {
    backgroundColor: colors.warning,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.xl,
    borderRadius: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    ...shadows.md,
  },
  syncButtonDisabled: {
    backgroundColor: colors.gray[400],
    ...shadows.sm,
  },
  syncButtonText: {
    color: colors.white,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
  },
  statsSection: {
    backgroundColor: colors.white,
    margin: spacing.xl,
    padding: spacing.xxl,
    borderRadius: spacing.xl,
    ...shadows.lg,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.lg,
  },
  statCard: {
    flex: 1,
    minWidth: "45%",
    position: "relative",
    backgroundColor: colors.gray[50],
    padding: spacing.xl,
    borderRadius: spacing.lg,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.default,
    ...shadows.sm,
  },
  statIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  statContent: {
    alignItems: "center",
  },
  statValue: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.extraBold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  statTitle: {
    fontSize: fontSize.xs,
    color: colors.text.secondary,
    fontWeight: fontWeight.semiBold,
    textAlign: "center",
  },
  statDecoration: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.primary,
  },
  section: {
    backgroundColor: colors.white,
    margin: spacing.xl,
    padding: spacing.xxl,
    borderRadius: spacing.xl,
    ...shadows.lg,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  fileInfoCard: {
    gap: spacing.lg,
  },
  fileInfoItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.gray[50],
    padding: spacing.lg,
    borderRadius: spacing.md,
    gap: spacing.md,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  fileCount: {
    fontSize: fontSize.md,
    color: colors.text.primary,
    fontWeight: fontWeight.medium,
  },
  fileSize: {
    fontSize: fontSize.md,
    color: colors.text.primary,
    fontWeight: fontWeight.medium,
  },
  settingsContainer: {
    gap: spacing.xs,
  },
  settingItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xs,
    borderRadius: spacing.md,
    backgroundColor: colors.gray[50],
    marginBottom: spacing.sm,
  },
  settingLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  settingIcon: {
    backgroundColor: colors.white,
    borderRadius: spacing.md,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  settingText: {
    fontSize: fontSize.md,
    color: colors.text.primary,
    fontWeight: fontWeight.medium,
  },
  logoutButton: {
    backgroundColor: colors.white,
    margin: spacing.xl,
    padding: spacing.xl,
    borderRadius: spacing.lg,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: spacing.md,
    ...shadows.lg,
    borderWidth: 2,
    borderColor: "#fecaca",
  },
  logoutText: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.error,
  },
})
