import { StyleSheet, Platform } from "react-native"
import { colors, spacing, borderRadius, fontSize, fontWeight, shadows } from "../theme"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  networkStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    gap: spacing.sm,
  },
  networkOnline: {
    backgroundColor: colors.success,
  },
  networkOffline: {
    backgroundColor: colors.warning,
  },
  networkStatusText: {
    color: colors.white,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semiBold,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
    paddingHorizontal: spacing.huge,
  },
  emptyTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.bold,
    color: colors.text.secondary,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
    textAlign: "center",
  },
  emptyText: {
    fontSize: fontSize.md,
    color: colors.text.tertiary,
    textAlign: "center",
    lineHeight: 24,
  },
  taskCard: {
    backgroundColor: colors.white,
    margin: spacing.sm,
    padding: spacing.sm,
    borderRadius: spacing.sm,
    ...shadows.lg,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  taskHeader: {
    marginBottom: spacing.sm,
  },
  taskBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.gray[100],
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: spacing.md,
    alignSelf: "flex-start",
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  taskId: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.primary,
  },
  taskText: {
    fontSize: fontSize.lg,
    color: colors.text.primary,
    lineHeight: 28,
    fontWeight: fontWeight.medium,
  },
  recordingSection: {
    backgroundColor: colors.white,
    margin: spacing.sm,
    padding: spacing.xl,
    borderRadius: spacing.sm,
    alignItems: "center",
    ...shadows.lg,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  sectionTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  recordingControls: {
    alignItems: "center",
    marginBottom: spacing.md,
  },
  recordButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacing.sm,
    position: "relative",
    ...shadows.xl,
  },
  recordButtonActive: {
    backgroundColor: colors.error,
  },
  recordButtonInner: {
    width: "100%",
    height: "100%",
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  pulseRing1: {
    position: "absolute",
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(239, 68, 68, 0.3)",
    zIndex: 1,
  },
  pulseRing2: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    zIndex: 0,
  },
  recordingTime: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.extraBold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  recordingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fef2f2",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: spacing.xl,
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  recordingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.error,
    marginRight: spacing.sm,
  },
  recordingText: {
    fontSize: fontSize.sm,
    color: colors.error,
    fontWeight: fontWeight.semiBold,
  },
  playbackSection: {
    marginTop: spacing.sm,
    width: "100%",
    backgroundColor: colors.gray[50],
    borderRadius: spacing.sm,
    padding: spacing.md,
  },
  playbackHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  playbackTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semiBold,
    color: colors.success,
  },
  playbackControls: {
    flexDirection: "row",
    justifyContent: "center",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  controlButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    ...shadows.md,
  },
  playButton: {
    backgroundColor: "#f0fdf4",
    borderWidth: 2,
    borderColor: "#bbf7d0",
  },
  playButtonActive: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  stopButton: {
    backgroundColor: "#fffbeb",
    borderWidth: 2,
    borderColor: "#fcd34d",
  },
  deleteButton: {
    backgroundColor: "#fef2f2",
    borderWidth: 2,
    borderColor: "#fecaca",
  },
  progressContainer: {
    width: "100%",
    alignItems: "center",
  },
  progressText: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
    fontWeight: fontWeight.medium,
  },
  waveformContainer: {
    width: "100%",
  },
  progressBar: {
    width: "100%",
    height: 6,
    backgroundColor: colors.border.default,
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.success,
    borderRadius: 3,
  },
  transcriptionSection: {
    backgroundColor: colors.white,
    margin: spacing.sm,
    padding: spacing.sm,
    borderRadius: spacing.sm,
    ...shadows.lg,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  transcriptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  transcriptionHint: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    marginBottom: spacing.md,
    lineHeight: 20,
  },
  transcriptionInputContainer: {
    position: "relative",
  },
  transcriptionInput: {
    borderWidth: 2,
    borderColor: colors.border.default,
    borderRadius: spacing.sm,
    padding: spacing.md,
    fontSize: fontSize.sm,
    minHeight: 80,
    backgroundColor: colors.gray[50],
    color: colors.text.primary,
    lineHeight: 20,
    textAlignVertical: "top",
  },
  transcriptionCounter: {
    position: "absolute",
    bottom: spacing.sm,
    right: spacing.md,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.sm,
  },
  counterText: {
    fontSize: fontSize.xs,
    color: colors.text.secondary,
    fontWeight: fontWeight.medium,
  },
  uploadSection: {
    backgroundColor: colors.white,
    margin: spacing.xl,
    padding: spacing.xxl,
    borderRadius: spacing.xl,
    ...shadows.lg,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  uploadHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  uploadTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semiBold,
    color: colors.info,
  },
  uploadProgress: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  uploadProgressBar: {
    flex: 1,
    height: 8,
    backgroundColor: "#e0f2fe",
    borderRadius: 4,
    overflow: "hidden",
  },
  uploadProgressFill: {
    height: "100%",
    backgroundColor: colors.info,
    borderRadius: 4,
  },
  uploadProgressText: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    color: colors.info,
    minWidth: 50,
    textAlign: "center",
  },
  saveButton: {
    backgroundColor: colors.success,
    margin: spacing.sm,
    padding: spacing.md,
    borderRadius: spacing.sm,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: spacing.sm,
    ...shadows.lg,
  },
  saveButtonDisabled: {
    backgroundColor: colors.gray[400],
    ...shadows.sm,
  },
  saveButtonText: {
    color: colors.white,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
  },
})
