import { StyleSheet } from "react-native"
import { colors, spacing, borderRadius, fontSize, fontWeight, shadows } from "../theme"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: colors.primary,
    borderBottomLeftRadius: spacing.xxxl,
    borderBottomRightRadius: spacing.xxxl,
  },
  header: {
    paddingTop: 60,
    paddingBottom: spacing.xxl,
    paddingHorizontal: spacing.xxl,
    zIndex: 1,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: spacing.xl,
  },
  titleSection: {
    flex: 1,
  },
  headerTitle: {
    fontSize: fontSize.xxxl,
    fontWeight: fontWeight.extraBold,
    color: colors.white,
    marginBottom: spacing.xs,
  },
  headerSubtitle: {
    fontSize: fontSize.md,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: fontWeight.medium,
  },
  taskCounter: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: spacing.xl,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  taskCountText: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.white,
  },
  progressSection: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    alignItems: "center",
  },
  progressText: {
    fontSize: fontSize.sm,
    color: "rgba(255, 255, 255, 0.9)",
    marginBottom: spacing.sm,
  },
  progressBar: {
    width: "100%",
    height: 6,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: spacing.sm,
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.success,
    borderRadius: 3,
  },
  progressLabel: {
    fontSize: fontSize.xs,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: fontWeight.medium,
  },
  listContainer: {
    padding: spacing.xl,
    flexGrow: 1,
    paddingTop: spacing.sm,
  },
  separator: {
    height: spacing.sm,
  },
  taskItem: {
    backgroundColor: colors.white,
    borderRadius: spacing.xl,
    padding: spacing.xl,
    flexDirection: "row",
    alignItems: "center",
    ...shadows.md,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  taskLeftSection: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  taskIdBadge: {
    backgroundColor: colors.gray[100],
    borderRadius: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    marginRight: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  taskIdText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.primary,
  },
  taskContent: {
    flex: 1,
  },
  taskLabel: {
    fontSize: fontSize.xs,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
    fontWeight: fontWeight.semiBold,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  taskText: {
    fontSize: fontSize.md,
    color: colors.text.primary,
    lineHeight: 24,
    fontWeight: fontWeight.medium,
  },
  taskRightSection: {
    alignItems: "center",
    gap: spacing.sm,
  },
  playIconContainer: {
    backgroundColor: colors.gray[100],
    borderRadius: spacing.xl,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: spacing.xxxl,
  },
  emptyIconContainer: {
    position: "relative",
    marginBottom: spacing.xxl,
  },
  sparkle1: {
    position: "absolute",
    top: -10,
    right: -5,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.warning,
  },
  sparkle2: {
    position: "absolute",
    bottom: -5,
    left: -10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.warningLight,
  },
  sparkle3: {
    position: "absolute",
    top: 10,
    left: -15,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#fef3c7",
  },
  emptyStateTitle: {
    fontSize: fontSize.xxxl,
    fontWeight: fontWeight.extraBold,
    color: colors.success,
    marginBottom: spacing.md,
    textAlign: "center",
  },
  emptyStateText: {
    fontSize: fontSize.lg,
    color: colors.text.secondary,
    textAlign: "center",
    lineHeight: 26,
    marginBottom: spacing.sm,
  },
  emptyStateSubtext: {
    fontSize: fontSize.md,
    color: colors.text.tertiary,
    textAlign: "center",
    fontWeight: fontWeight.medium,
  },
})
